### ISSUE TITLE
Offer of collaboration

### ISSUE THREAD

**Issue by anjakefala** [cldf/cookbook#6]
Hi!

I write documentation for VisiData and your kind words in its recipe left me feeling very heartwarmed. :)
I am particularly excited by this project because several of my dear friends are deeply involved in Linguistics.

We would like to offer our support and are excited to see/communicate on the helper scripts you came up with. Perhaps we can more fully integrate some of them into VisiData. :)

In any case, thanks again for the kind words and shoutout.

**Comment by xrotwang** [comment]
@anjakefala Hi and thanks a lot for reaching out! We think tools such as VisiData could be exactly what's missing to turn packages of CSV files (like our CLDF datasets) into first class "file types". From our point of view, built-in support for such package formats ([csvw](http://www.w3.org/TR/tabular-data-model/) or [Data Package](https://frictionlessdata.io/specs/data-package/)) would be the most convenient solution. But we already have support for converting CLDF datasets to an SQLite database (in our pycldf package) - and AFAICT SQLite can already be read by VisiData; so this could be an alternative.

But in any case, help with documentation and communication of any solution would be very welcome - since this may possibly be the biggest job ahead of us, considering current prestige of the command line in most of the Linguistics community :)

**Comment by chrzyki** [comment]
Thank you very much for the offer and for the awesome tool/project that is visidata! I'm still learning the ins and outs of everything visidata has to offer but I've already got a lot of ideas how we can use it to enhance our workflows.

I'll try to get some of the more basic tutorials ready in the next couple of days and it'd be super-cool if I could get our feedback on these (I'll just ping you if that's okay?). After that a look at the scripts would indeed be very helpful, thanks!

**Comment by anjakefala** [comment]
@chrzyki Of course! Feel free to ping me either here or to email me at anja.kefala (at) gmail.com.

@xrotwang Yes, SQLite filetypes can already be read by VisiData. :) (We do welcome feedback for any suggestions on improving that loader!) I would love to see if we could also expand support for some domain-specific filetypes. 

I can definitely help with documentation because I am currently trying to improve the existing documentation...so any engagement I can have with user scenarios would be lovely...

As a side note, have you looked into collaborating with [The Carpentries](https://carpentries.org/) in terms ofcommunication of solutions to the Linguistic community at large? They seem to very actively want to engage with expanding the toolkit of every academic discipline, so I would not be surprised with if there were already Linguists involved with them who were experimenting with introducing researchers to the terminal.

:bee:

**Comment by chrzyki** [comment]
That looks like a great resource and project, thank you! I hadn't heard of this before (maybe @xrotwang has). Will definitely try and see whether there is an angle for any type of collaboration.

Do you have a preferred way of receiving comments about the documentation? So far, the docs have been a godsend but should I notice anything I'll gladly report. :)

**Comment by anjakefala** [comment]
@chrzyki If you spot a problem, or have suggestions for improvement, open an issue on https://github.com/saulpw/visidata, please! :D
